language: rust
env:
  global:
    - secure: jHaQxUCPsFgcVfGn1Gw+GX+3GrmJjXOpEfHfoaeHz03r58IIzYD1mFL1/QjCPR8nn2X1GCuUzFaJtYB/1xmgYC6HZP7kFBGkygBEt0Jiem/lru328WNRD3/j9wQi1OL6+cTcNcz0+4oTiwvctqA8p3OcuKCr+VDiQnspq+orLHM=
    # GH_TOKEN
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - mv target/doc doc

#[ $TRAVIS_BRANCH = master ] && 
after_success: |
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=primes/index.html>' > doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n doc &&
  git push -qf https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
notifications:
  email:
    on_success: never